package com.ironhack.trailsservice.enums;

public enum Region {
    ALAVA,ALBACETE,ALICANTE,ALMERIA,ASTURIAS,AVILA,BADAJOZ,BARCELONA,BURGOS,CACERES,CADIZ,CANTABRIA,CASTELLON,CIUDAD_REAL,CORDOBA,LA_CORUÑA,
    CUENCA,GERONA,GRANADA,GUADALAJARA,GUIPUZCUA,HUELVA,HUESCA,ISLAS_BALEARES,JAEN,LEON,LERIDA,LUGO,MADRID,MALAGA,MELILLA,MURCIA,NAVARRA,OURENSE,
    PALENCIA,ISLAS_CANARIAS,PONTEVEDRA,LA_RIOJA,SALAMANCA,SEGOVIA,SEVILLA,SORIA,TARRAGONA,TERUEL,TOLEDO,VALENCIA,VALLADOLID,
    VIZCAYA,ZAMORA,ZARAGOZA

}
